apiVersion: v2
name: pagopa-biz-events-service
description: Microservice for exposing REST APIs about payment receipts.
type: application
version: 0.136.0
appVersion: 0.1.90-1-PAGOPA-3442
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
